[package]
name = "branch-context"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
chrono = { version = "0.4.40", features = ["serde"] }
rand = "0.9.0"
serde = { version = "1.0.218", optional = true, features = ["derive"] }

[features]
serde = ["dep:serde"]
